import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const CharactersDefaultPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        // META DATA GOES HERE, schemas etc
      </Head>
      <main />
    </div>
  );
};

export const getStaticProps = () => {
  return {
    redirect: {
      destination: "/characters/1",
      permanent: false,
    },
  };
};

export default CharactersDefaultPage;
