import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import LayoutDefault from "../components/layouts/LayoutDefault";

const ErrorPage: NextPage = () => {
  return (
    <div>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <LayoutDefault noBackground>
            <h1>404 - Page Not Found</h1>
            <Link href="/">Go to Homepage</Link>
          </LayoutDefault>
        </main>
      </div>
    </div>
  );
};

export default ErrorPage;
