import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import LayoutDefault from "../components/layouts/LayoutDefault";

const Home: NextPage = () => {
  return (
    <div>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          // Meta data goes here
        </Head>
        <main>
          <LayoutDefault noBackground>
            <h1>Welcome home!</h1>
            <Link href="/characters">View Characters</Link>
          </LayoutDefault>
        </main>
      </div>
    </div>
  );
};

export default Home;
